name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release and update helm chart
    steps:
      - uses: catalystsquad/action-semantic-release-general@v1
        with:
          token: ${{ secrets.AUTOMATION_PAT }}